import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Card from "../components/Card";
import styled from "styled-components";
import { useState } from "react";

let names = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "0", "J", "Q", "K"];
let values = {
  A: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  0: 10,
  J: 10,
  Q: 10,
  K: 10,
};
let suits = ["C"];
export default function Home() {
  const [selectedCards, setSelectedCards] = useState([]);
  const DECK_SIZE = 6;
  const [userCards, setUserCards] = useState([]);
  const [userEnabled, setuserEnabled] = useState(false);
  const [courpierEnabled, setcourpierEnabled] = useState(false);
  const [userPoints, setUserPoints] = useState(0);
  const [totalSelectedCards, setTotalSelectedCards] = useState(0);
  const [totalPictureCards, settotalPictureCards] = useState(0);
  const [totalLowCards, settotalLowCards] = useState(0);
  const [totalHighCards, settotalHighCards] = useState(0);
  const [totalValue, setTotalValue] = useState(0);
  const CardPicker = styled.div`
    display: flex;
    flex-direction: column;
    gap: 1rem;
    width: 60%;
  `;

  const cardChange = (e) => {
    if (
      e.target.id[0] == "2" ||
      e.target.id[0] == "3" ||
      e.target.id[0] == "4" ||
      e.target.id[0] == "5" ||
      e.target.id[0] == "6"
    ) {
      settotalLowCards(totalLowCards + 1);
    }
    if (
      e.target.id[0] == "7" ||
      e.target.id[0] == "8" ||
      e.target.id[0] == "9"
    ) {
      settotalHighCards(totalHighCards + 1);
    }
    if (
      e.target.id[0] == "J" ||
      e.target.id[0] == "Q" ||
      e.target.id[0] == "K" ||
      e.target.id[0] == "0"
    ) {
      console.log("here");
      settotalPictureCards(totalPictureCards + 1);
      if (!(e.target.id[0] == "A")) {
        setTotalValue(totalValue - 2);
      }
    }
    if (e.target.id[0] == "4" || e.target.id[0] == "5") {
      setTotalValue(totalValue + 2);
    }
    if (
      e.target.id[0] == "2" ||
      e.target.id[0] == "3" ||
      e.target.id[0] == "6" ||
      e.target.id[0] == "7"
    ) {
      setTotalValue(totalValue + 1);
    }
    if (userEnabled) {
      if (Object.keys(userCards).includes(e.target.id)) {
        setUserCards([
          ...userCards,
          { [e.target.id]: userCards[e.target.id] + 1 },
        ]);
      } else {
        setUserCards([...userCards, { [e.target.id]: 0 }]);
      }
      setUserPoints(userPoints + values[e.target.id[0]]);
    }

    if (selectedCards.find((item) => Object.keys(item)[0] == e.target.id)) {
      setSelectedCards(
        selectedCards.map((item) => {
          if (Object.keys(item)[0] == e.target.id) {
            return { [e.target.id]: item[e.target.id] + 1 };
          } else {
            return item;
          }
        })
      );
    } else {
      setSelectedCards([...selectedCards, { [e.target.id]: 1 }]);
    }
    setTotalSelectedCards(totalSelectedCards + 1);
  };
  const reset = () => {
    setSelectedCards([]);
    setTotalSelectedCards(0);
    settotalPictureCards(0);
    settotalLowCards(0);
    settotalHighCards(0);
    setTotalValue(0);
  };
  const resetMyCards = () => {
    setUserCards([]);
    setCourpierCards([]);
    setUserPoints(0);
    setuserEnabled(false);
  };

  const enableButton = (e) => {
    if (e.target.id == "user") {
      setuserEnabled(true);
      if (courpierEnabled) {
        setcourpierEnabled(false);
      }
      return;
    } else if (e.target.id == "courpier") {
      setcourpierEnabled(true);
      if (userEnabled) {
        setuserEnabled(false);
      }
      return;
    }
    setuserEnabled(false);
    setcourpierEnabled(false);
  };
  const calculateChance = () => {
    const maximumValue = 21 - userPoints;
    let lostCases = 0;
    let allCards = suits.map((suit) =>
      names.map((name) => {
        return { [name + suit]: 4 };
      })
    );
    for (const card of allCards.flat()) {
      let cardId = Object.keys(card)[0];
      let foundValue = selectedCards.find(
        (item) => Object.keys(item)[0] == cardId
      );
      if (foundValue) {
        card[cardId] = card[cardId] - foundValue[cardId];
      }
    }
    let remainingCards = allCards
      .flat()
      .filter((item) => Object.values(item)[0] > 0);
    for (const card of remainingCards) {
      let cardId = Object.keys(card)[0];
      let cardValue = values[cardId[0]];
      let cardTimes = card[cardId];
      if (cardValue > maximumValue) {
        lostCases += cardTimes;
      }
    }
    let totalRemainingCards = remainingCards.reduce(
      (acc, item) => acc + Object.values(item)[0],
      0
    );
    let chance = (lostCases / totalRemainingCards) * 100;
    return chance;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-[#252525] p-5 flex flex-row w-full">
        <div className="flex flex-row justify-around w-[75%] my-5">
          {suits.map((suit, index) => {
            return (
              <div
                key={index}
                className="w-full flex relative items-center cursor-pointer text-[8rem] justify-center mx-[2rem] p-[1rem] flex-col"
              >
                {names.map((name, cardIndex) => {
                  return (
                    <div
                      className="absolute hover:translate-x-2 transition-all  ease-in-out"
                      id={name + suit}
                      style={
                        selectedCards.includes(name + suit)
                          ? { top: cardIndex * 57 }
                          : { top: cardIndex * 57 }
                      }
                      key={cardIndex}
                      onClick={cardChange}
                    >
                      <img
                        src={`https://www.deckofcardsapi.com/static/img/${
                          name + suit
                        }.png`}
                        id={name + suit}
                        height={150}
                        width={150}
                      />
                      <div
                        className="bg-[#252525] absolute top-0 right-[3px] rounded-full flex justify-center items-center"
                        id={name + suit}
                        onClick={cardChange}
                        style={{ width: 30, height: 30 }}
                      >
                        <h1 className="text-white absolute text-sm text-center">
                          {selectedCards.find(
                            (item) => Object.keys(item)[0] == name + suit
                          )
                            ? selectedCards.find(
                                (item) => Object.keys(item)[0] == name + suit
                              )[name + suit]
                            : 0}
                        </h1>
                      </div>
                    </div>
                  );
                })}
              </div>
            );
          })}
        </div>
        <div className="w-[30%]  mx-5 ">
          <div className="text-xl text-center text-[#f0f0f0] font-bold my-11">
            <h1>Probabilities</h1>
          </div>

          <div className="flex flex-col justify-between gap-6">
            <div className="text-[#f0f0f0] font-bold flex flex-row gap-5 h-[35px] items-center">
              <h1>Chance For 2-3-4-5-6</h1>
              <span>
                {totalLowCards > 0
                  ? (
                      ((DECK_SIZE * 20 - totalLowCards) /
                        (DECK_SIZE * 52 - totalSelectedCards)) *
                      100
                    ).toFixed(2)
                  : (
                      ((DECK_SIZE * 20) /
                        (DECK_SIZE * 52 - totalSelectedCards)) *
                      100
                    ).toFixed(2)}
                %
              </span>
              <span
                className="text-sm font-bold"
                style={
                  (
                    ((DECK_SIZE * 20 - totalLowCards) /
                      (DECK_SIZE * 52 - totalSelectedCards)) *
                      100 -
                    38.46
                  ).toFixed(2) < 0
                    ? { color: "red" }
                    : { color: "#21db53" }
                }
              >
                {" "}
                %
                {(
                  ((DECK_SIZE * 20 - totalLowCards) /
                    (DECK_SIZE * 52 - totalSelectedCards)) *
                    100 -
                  38.46
                ).toFixed(2)}
              </span>
            </div>
            <div className="text-[#f0f0f0] font-bold flex flex-row gap-5 h-[35px] items-center">
              <h1>Chance For 7-8-9</h1>
              <span>
                {totalHighCards > 0
                  ? (
                      ((DECK_SIZE * 12 - totalHighCards) /
                        (DECK_SIZE * 52 - totalSelectedCards)) *
                      100
                    ).toFixed(2)
                  : (
                      ((DECK_SIZE * 12) /
                        (DECK_SIZE * 52 - totalSelectedCards)) *
                      100
                    ).toFixed(2)}
                %
              </span>
              <span
                className="text-sm font-bold"
                style={
                  (
                    ((DECK_SIZE * 12 - totalHighCards) /
                      (DECK_SIZE * 52 - totalSelectedCards)) *
                      100 -
                    23.08
                  ).toFixed(2) < 0
                    ? { color: "red" }
                    : { color: "#21db53" }
                }
              >
                {" "}
                %
                {(
                  ((DECK_SIZE * 12 - totalHighCards) /
                    (DECK_SIZE * 52 - totalSelectedCards)) *
                    100 -
                  23.08
                ).toFixed(2)}
              </span>
            </div>
            <div className="text-[#f0f0f0] font-bold flex flex-row gap-5 h-[35px] items-center ">
              <h1>Chance For Picture Card and 10</h1>

              <span>
                {totalPictureCards > 0
                  ? (
                      ((DECK_SIZE * 16 - totalPictureCards) /
                        (DECK_SIZE * 52 - totalSelectedCards)) *
                      100
                    ).toFixed(2)
                  : (
                      ((DECK_SIZE * 16) /
                        (DECK_SIZE * 52 - totalSelectedCards)) *
                      100
                    ).toFixed(2)}
                %
              </span>

              <span
                className="text-sm font-bold"
                style={
                  (
                    ((DECK_SIZE * 16 - totalPictureCards) /
                      (DECK_SIZE * 52 - totalSelectedCards)) *
                      100 -
                    30.77
                  ).toFixed(2) < 0
                    ? { color: "red" }
                    : { color: "#21db53" }
                }
              >
                {" "}
                %
                {(
                  ((DECK_SIZE * 16 - totalPictureCards) /
                    (DECK_SIZE * 52 - totalSelectedCards)) *
                    100 -
                  30.77
                ).toFixed(2)}
              </span>
            </div>
            <div className="text-[#f0f0f0] font-bold flex flex-row gap-5 h-[35px] items-center">
              <h1>Remaining Aces</h1>
              <span>
                {DECK_SIZE * 4} /{" "}
                {selectedCards.filter((card) => Object.keys(card)[0][0] == "A")
                  .length > 0
                  ? DECK_SIZE * 4 -
                    Object.values(
                      selectedCards.filter(
                        (card) => Object.keys(card)[0][0] == "A"
                      )[0]
                    )[0]
                  : DECK_SIZE * 4}{" "}
              </span>
            </div>
            <div className="text-[#f0f0f0] font-bold flex flex-row gap-5 h-[35px] items-center">
              <h1>HI OPT Count</h1>
              <span>{totalValue}</span>
            </div>
            <div className="text-[#f0f0f0] font-bold flex flex-row gap-5 h-[35px] items-center">
              <h1>True Count</h1>
              <span>
                {(
                  totalValue /
                  ((DECK_SIZE * 52 - totalSelectedCards) / 52)
                ).toFixed(2)}
              </span>
            </div>

            <div>
              <button
                className="bg-[#f0f0f0] text-[#252525] font-bold py-2 px-4 rounded-md"
                onClick={reset}
              >
                Reset
              </button>
              <button
                className="bg-[#f0f0f0] text-[#252525] font-bold py-2 px-4 rounded-md mx-5"
                onClick={resetMyCards}
              >
                Reset My Cards
              </button>
            </div>
            <div style={{ height: "0.2rem" }}></div>

            <CardPicker>
              <button
                onClick={enableButton}
                id="general"
                className={
                  !courpierEnabled && !userEnabled
                    ? "bg-red-500 text-[#252525] font-bold py-2 px-4 rounded-md"
                    : "bg-[#f0f0f0] text-[#252525] font-bold py-2 px-4 rounded-md opacity-50"
                }
              >
                General
              </button>
            </CardPicker>
            <div style={{ height: "0.2rem" }}></div>
            <CardPicker>
              <button
                id="user"
                onClick={enableButton}
                className={
                  userEnabled
                    ? "bg-red-500 text-[#252525] font-bold py-2 px-4 rounded-md"
                    : "bg-[#f0f0f0] text-[#252525] font-bold py-2 px-4 rounded-md opacity-50"
                }
              >
                Enable My Card
              </button>
            </CardPicker>
            <div style={{ height: "0.2rem" }}></div>
          </div>
        </div>
      </main>
    </>
  );
}
